# Generated by Django 5.1 on 2024-08-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_pessoa_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Meta',
        ),
    ]
