# Generated by Django 5.0.8 on 2024-08-24 12:44
import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='previsao_conclusao',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='status',
            field=models.CharField(choices=[('executando', 'Executando'), ('desistiu', 'Desistiu'), ('concluido', 'Concluído')], default='executando', max_length=10),
        ),
        migrations.AddField(
            model_name='meta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meta', to=settings.AUTH_USER_MODEL),
        ),
    ]
