# Generated by Django 5.0.8 on 2024-08-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_meta_data_inicio_meta_previsao_conclusao_meta_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('executando', 'Executando'), ('desistiu', 'Desistiu'), ('concluido', 'Concluído')], default='executando', max_length=10),
        ),
    ]
