# Generated by Django 5.0.8 on 2024-08-24 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='todolist.meta'),
        ),
    ]
