# Generated by Django 5.0.8 on 2024-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_task_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
