# Generated by Django 5.0.8 on 2024-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_meta_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
