# Generated by Django 5.0.8 on 2024-09-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("PDF", "PDF")], max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
            },
        ),
        migrations.CreateModel(
            name="YearlyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("total_value", models.FloatField()),
            ],
            options={
                "verbose_name": "Dado Anual",
                "verbose_name_plural": "Dados Anuais",
            },
        ),
        migrations.CreateModel(
            name="MonthlyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("data_value", models.FloatField()),
            ],
            options={
                "verbose_name": "Dado Mensal",
                "verbose_name_plural": "Dados Mensais",
                "unique_together": {("month", "year")},
            },
        ),
    ]
